from django.conf import settings


SOCIAL_AUTO_APPROVE = getattr(settings, 'SOCIAL_TWITTER_AUTO_APPROVE', 1)
SOCIAL_FACEBOOK_INTERVAL = getattr(settings, 'SOCIAL_FACEBOOK_INTERVAL', 15)
SOCIAL_TWITTER_INTERVAL = getattr(settings, 'SOCIAL_TWITTER_INTERVAL', 15)